remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark"
title: "::1 | Stories of future /dev/null"

plugins:
  - jekyll-include-cache
 
 defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name: "Christian A. Benstein"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Azure engeneer @ Intercept"
  location: "NL"
 
# Relevante helpt --> https://mmistakes.github.io/minimal-mistakes/docs/configuration/# 

# Ook leuk:

# http://mattvh.github.io/solar-theme-jekyll/
# http://themes.jekyllrc.org/darcli/
# https://webjeda.com/hagura/
