remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: "::1 | Stories of future /dev/null"

plugins:
  - jekyll-include-cache
  
author:
  name     : "Christian A. Benstein"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Azure Engineer @ Intercept"
  location : "localhost, NL" 
 
# Relevante helpt --> https://mmistakes.github.io/minimal-mistakes/docs/configuration/# 

# Ook leuk:

# http://mattvh.github.io/solar-theme-jekyll/
# http://themes.jekyllrc.org/darcli/
# https://webjeda.com/hagura/
